version: "3.7"

services:
  electrs:
    container_name: electrs
    image: getumbrel/electrs:v0.10.7
    restart: always
    user: "${APP_ELECTRS_USER_INFO}"
    ports:
      - "${APP_ELECTRS_PORT}:${APP_ELECTRS_PORT}"
    volumes:
      - "../volumes/bitcoin/node:/data/.bitcoin:ro"
      - "../volumes/electrs:/data"
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "bitcoin"
      ELECTRS_DAEMON_RPC_ADDR: "${APP_BITCOIND_IP}:${APP_BITCOIND_RPC_PORT}"
      ELECTRS_DAEMON_P2P_ADDR: "${APP_BITCOIND_IP}:${APP_BITCOIND_P2P_PORT}"
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:${APP_ELECTRS_PORT}"
      ELECTRS_SERVER_BANNER: "Umbrel Electrs"
      ELECTRS_DB_DIR: "/data/db"
    networks:
      default:
        ipv4_address: "${APP_ELECTRS_IP}"
  electrs_gui:
    container_name: electrs_gui
    image: getumbrel/umbrel-electrs:v1.0.4
    restart: on-failure
    depends_on: [electrs]
    ports:
      - "${APP_ELECTRS_GUI_PORT}:${APP_ELECTRS_GUI_PORT}"
    environment:
      ELECTRUM_HIDDEN_SERVICE: "${APP_ELECTRS_RPC_HIDDEN_SERVICE}"
      ELECTRUM_LOCAL_SERVICE: "${DEVICE_DOMAIN_NAME}"
      ELECTRS_HOST: "${APP_ELECTRS_IP}"
      BITCOIN_HOST: "${APP_BITCOIND_IP}"
      RPC_USER: "${APP_BITCOIN_RPC_USERNAME}"
      RPC_PASSWORD: "${APP_BITCOIN_RPC_PASSWORD}"
      RPC_PORT: "${APP_BITCOIND_RPC_PORT}"
    networks:
      default:
        ipv4_address: "${APP_ELECTRS_GUI_IP}"
  btc_explorer:
    container_name: btc_explorer
    image: getumbrel/btc-rpc-explorer:v3.4.0
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_MEMPOOL_PORT}:${APP_MEMPOOL_PORT}"
    environment:
      BTCEXP_HOST: "0.0.0.0"
      BTCEXP_PORT: "${APP_MEMPOOL_PORT}"
      BTCEXP_BITCOIND_HOST: "${APP_BITCOIND_IP}"
      BTCEXP_BITCOIND_PORT: "${APP_BITCOIND_RPC_PORT}"
      BTCEXP_BITCOIND_USER: "${APP_BITCOIN_RPC_USERNAME}"
      BTCEXP_BITCOIND_PASS: "${APP_BITCOIN_RPC_PASSWORD}"
      BTCEXP_ADDRESS_API: "electrumx"
      BTCEXP_ELECTRUMX_SERVERS: "tcp://${APP_ELECTRS_IP}:${APP_ELECTRS_PORT}"
      DEBUG: "btcexp:*,electrumClient"
      BTCEXP_SLOW_DEVICE_MODE: "true"
      BTCEXP_NO_INMEMORY_RPC_CACHE: "true"
      BTCEXP_RPC_ALLOWALL: "false"
      BTCEXP_BASIC_AUTH_PASSWORD: ""
      BTCEXP_PRIVACY_MODE: "false"
      BTCEXP_LOCAL_CURRENCY: "aud"
      BTCEXP_UI_TIMEZONE: "local"
    networks:
      default:
        ipv4_address: "${APP_MEMPOOL_IP}"
  mempool_space_web:
    container_name: mempool_space_web
    image: mempool/frontend:v3.0.1
    user: "${APP_MEMPOOL_USER_INFO}"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "${APP_MEMPOOL_PORT}:${APP_MEMPOOL_PORT}"
    command: "./wait-for mempool_space_db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    environment:
      FRONTEND_HTTP_PORT: "${APP_MEMPOOL_PORT}"
      BACKEND_MAINNET_HTTP_HOST: "${APP_MEMPOOL_API_IP}"
      NGINX_PORT: "${APP_MEMPOOL_PORT}"
      NGINX_HOSTNAME: "${APP_MEMPOOL_API_IP}"
      LIGHTNING_DETECTED_PORT: "${APP_LIGHTNING_NODE_PORT}"
    networks:
      default:
        ipv4_address: "${APP_MEMPOOL_IP}"
  mempool_space_api:
    container_name: mempool_space_api
    image: mempool/backend:v3.0.1
    user: "${APP_MEMPOOL_USER_INFO}"
    init: true
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh mempool_space_db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - "../volumes/mempool/data:/backend/cache"
      - "../volumes/lightning/lnd:/lnd:ro"
    environment:
      CORE_RPC_HOST: "${APP_BITCOIND_IP}"
      CORE_RPC_PORT: "${APP_BITCOIND_RPC_PORT}"
      CORE_RPC_USERNAME: "${APP_BITCOIN_RPC_USERNAME}"
      CORE_RPC_PASSWORD: "${APP_BITCOIN_RPC_PASSWORD}"
      ELECTRUM_HOST: "${APP_ELECTRS_IP}"
      ELECTRUM_PORT: "${APP_ELECTRS_PORT}"
      ELECTRUM_TLS: "false"
      DATABASE_HOST: "${APP_MEMPOOL_DB_IP}"
      DATABASE_PORT: "3306"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "${APP_MEMPOOL_DB_USERNAME}"
      DATABASE_PASSWORD: "${APP_MEMPOOL_DB_PASSWORD}"
      MEMPOOL_HTTP_PORT: "${APP_MEMPOOL_PORT}"
      MEMPOOL_CACHE_DIR: "/backend/cache"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"
      MEMPOOL_INDEXING_BLOCKS_AMOUNT: "52560"
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: "info"
      LIGHTNING_ENABLED: "false" # Enable as needed.
      LIGHTNING_BACKEND: "lnd"
      LIGHTNING_STATS_REFRESH_INTERVAL: 3600
      LIGHTNING_GRAPH_REFRESH_INTERVAL: 3600
      LND_TLS_CERT_PATH: "/lnd/tls.cert"
      LND_MACAROON_PATH: "/lnd/data/chain/bitcoin/${APP_CRYPTO_NETWORK}/readonly.macaroon"
      LND_REST_API_URL: "https://${APP_LIGHTNING_NODE_IP}:${APP_LIGHTNING_NODE_REST_PORT}"
      LND_TIMEOUT: 120000
      NODE_OPTIONS: "--max-old-space-size=2048"
    networks:
      default:
        ipv4_address: "${APP_MEMPOOL_API_IP}"
  mempool_space_db:
    container_name: mempool_space_db
    image: mariadb:10.5.12
    user: "root" # Change as needed.
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - "../volumes/mempool/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "${APP_MEMPOOL_DB_USERNAME}"
      MYSQL_PASSWORD: "${APP_MEMPOOL_DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${APP_MEMPOOL_DB_ROOT_PASSWORD}"
    networks:
      default:
        ipv4_address: "${APP_MEMPOOL_DB_IP}"
