version: "3.7"

services:
  tor:
    container_name: tor
    image: lncm/tor:0.4.7.13
    restart: on-failure
    user: "${APP_TOR_USER_INFO}"
    volumes:
      - "../volumes/tor/torrc/torrc:/etc/tor/torrc:ro"
      - "../volumes/tor/data:/data"
    environment:
      HOME: "/tmp"
    networks:
      default:
        ipv4_address: "${APP_TOR_IP}"
  i2pd:
    container_name: i2pd
    image: purplei2p/i2pd:release-2.54.0
    command: "${APP_I2PD_COMMAND}"
    restart: on-failure
    user: "root"
    volumes:
      - "../volumes/i2pd:/home/i2pd/data"
    networks:
      default:
        ipv4_address: "${APP_I2PD_IP}"
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "${APP_NETWORK_SUBNET}"
