version: "3.7"

services:
  bitcoin:
    container_name: bitcoin
    image: ghcr.io/getumbrel/umbrel-bitcoin:v1.0.4-core.v29.1
    restart: on-failure
    user: "${APP_BITCOIND_USER_INFO}"
    stop_grace_period: 15m30s
    ports:
      - "${APP_BITCOIND_P2P_PORT}:${APP_BITCOIND_P2P_PORT}"
      - "${APP_BITCOIND_RPC_PORT}:${APP_BITCOIND_RPC_PORT}"
      - "${APP_BITCOIN_GUI_PORT}:3000"
    volumes:
      - "../volumes/bitcoin/node:/data/.bitcoin"
      - "../volumes/bitcoin/app:/data/app"
    environment:
      BITCOIND_EXTRA_ARGS: "${APP_BITCOIN_EXTRA_ARGS}"
      APPS_SUBNET: "${APP_NETWORK_SUBNET}"
      P2P_PORT: "${APP_BITCOIND_P2P_PORT}"
      P2P_WHITEBIND_PORT: "${APP_BITCOIND_P2P_WHITEBIND_PORT}"
      RPC_PORT: "${APP_BITCOIND_RPC_PORT}"
      TOR_PORT: "${APP_BITCOIND_TOR_PORT}"
      ZMQ_RAWBLOCK_PORT: "${APP_BITCOIND_PUB_RAW_BLOCK_PORT}"
      ZMQ_RAWTX_PORT: "${APP_BITCOIND_PUB_RAW_TX_PORT}"
      ZMQ_HASHBLOCK_PORT: "${APP_BITCOIN_ZMQ_HASHBLOCK_PORT}"
      ZMQ_SEQUENCE_PORT: "${APP_BITCOIN_ZMQ_SEQUENCE_PORT}"
      ZMQ_HASHTX_PORT: "${APP_BITCOIN_ZMQ_HASHTX_PORT}"
      TOR_HOST: "${APP_TOR_IP}"
      TOR_SOCKS_PORT: "${APP_TOR_SOCKS_PORT}"
      TOR_CONTROL_PORT: "${APP_TOR_CONTROL_PORT}"
      TOR_CONTROL_PASSWORD: "${APP_TOR_PROXY_PASSWORD}"
      I2P_HOST: "${APP_I2PD_IP}"
      I2P_SAM_PORT: "${APP_I2PD_PORT}"
      BITCOIND_IP: "${APP_BITCOIND_IP}"
      RPC_USER: "${APP_BITCOIN_RPC_USERNAME}"
      RPC_PASS: "${APP_BITCOIN_RPC_PASSWORD}"
      DEVICE_DOMAIN_NAME: "${DEVICE_DOMAIN_NAME}"
      P2P_HIDDEN_SERVICE: "${APP_BITCOIN_P2P_HIDDEN_SERVICE}"
      RPC_HIDDEN_SERVICE: "${APP_BITCOIN_RPC_HIDDEN_SERVICE}"
      DEFAULT_CHAIN: "${APP_BITCOIN_DEFAULT_CHAIN}"
      BITCOIN_DIR: "/data/.bitcoin"
      APP_STATE_DIR: "/data/app"
    networks:
      default:
        ipv4_address: "${APP_BITCOIND_IP}"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "${APP_NETWORK_SUBNET}"
